### PR TITLE
Use spinkit as external library to show a loading animation in the to…

### PR DESCRIPTION
**Pull request by mhebing**
Alternative to #192

### CODE REVIEW

**Comment by afuetterer** [comment]
How can I test this?

**Comment by mhebing** [comment]
You should be able to add my fork as a second remote in your repository, doing something like the following (basically replacing `origin` with `mhebing` as the remote):

```
git remote add mhebing <link to my repo using either https or ssl>
git fetch mhebing
git checkout mhebing/<branch>
```

**Comment by afuetterer** [comment]
Got it.
When do I see the spinner spinning?

**Comment by mhebing** [comment]
dor

**Comment by afuetterer** [comment]
I see the spinner spinning. The question is: Why does it take so long to load the table?

**Pull request merged**
