### PR TITLE
quickfix for long datasets, see #1287

### PR DESCRIPTION
**Pull request by mpahl**
Every dataset gets an entry.
If its not in the json file, it remains empty.

Close: #1287

### CODE REVIEW

**Comment by hansendx** [comment]
What does this to to the script?
Are the variables excluded from script generation or do we get a faulty script?
Users should get feedback for the variables, that are excluded.
Otherwise they might work with unexpected results.

**Comment by mpahl** [comment]
not_prozessed

**Comment by mpahl** [comment]
Variables from datasets that are not included in the JSON are in the category not processed.

**Comment by hansendx** [comment]
Cleaned this up in https://github.com/ddionrails/ddionrails/pull/1309

**Pull request closed without merging**
