### PR TITLE
547: Refactor title and title_de methods in Question and Variable

### PR DESCRIPTION
**Pull request by afuetterer**
## Proposed changes

This PR introduces the following changes to the codebase.
- move logic from title() and title_de() in Question and Variable to ModelMixin
- add test cases

Related issue(s): #547

## Types of changes

- Breaking Change

## Checklist

- I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by afuetterer** [comment]
@hansendx Should I change the interface of the title() method on the Mixin to accept a language argument that default to "en"?

**Comment by hansendx** [comment]
I would personally avoid args/kwargs in most cases since they can make the function harder to understand.
So something like  `language: str="en"` would be good in my opinion.

**Comment by afuetterer** [comment]
I agree.
The problem in the codacy review is the conflicting interfaces.

Mixin:
https://github.com/ddionrails/ddionrails/blob/166dab08130887561689bd20a3d9334ef0fdb2ee/ddionrails/base/mixins.py#L108-L121

Question:
https://github.com/ddionrails/ddionrails/blob/1c46de8650f912808a2337980025ecf653911742/ddionrails/instruments/models/question.py#L166-L182

Every model that inherits from the Mixin inherits the title() method.

I think they basically do the same thing, except for the language switch?

Return label if it is defined.
Otherwise return name.

Should we change the Mixin.title() then?

**Comment by afuetterer** [comment]
Rebased and fixed merge conflict.

**Pull request merged**
