### PR TITLE
[WIP] chore: add lint job in CI

### PR DESCRIPTION
**Pull request by afuetterer**
## Proposed changes

This additional CI job might help with contributors not using pre-commit locally. The lint job could run and potentially fail early, before building the docker containers. Running "pre-commit" in the docker container is of course also an option. But this might fail faster and safe some compute time.

What do you think, @hansendx?

## Types of changes

- Bugfix (non-breaking change which fixes an issue)

## Checklist

- no code affected

### CODE REVIEW

**Comment by afuetterer** [comment]
Well... cannot even install. Will fix this...

**Comment by afuetterer** [comment]
Okay, it might be easier to run this in the docker container, I guess

**Comment by hansendx** [comment]
Thank you for the pull request.

I have a few thoughts:

- ubuntu-latest [should](https://github.com/actions/runner-images#support-policy) have several pre-installed [python versions](https://github.com/actions/runner-images/blob/releases/ubuntu22/20230227/images/linux/Ubuntu2204-Readme.md#python), one of them should be sufficient for this job. So i wouldn't add a new action for that.
- I would skip the Pipfile and install the needed tools directly.
- I would call the tools directly, not through pre-commit.
- I would run the tools only on changed files. 

Addition to the last point: I have done this with GitLab Pipeline Jobs. There, the job gets an env var that contains the hash for the last commit. So you can use this to list changed files via the git cli.
There does not seem to be such an env var in the GitHub Job.
We could, from my understanding of it, parse this from the [PushEvent](https://docs.github.com/en/webhooks-and-events/events/github-event-types#pushevent) data, stored at [GITHUB_EVENT_PATH](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)

**Comment by afuetterer** [comment]
Answers inline.

> Thank you for the pull request.
> 
> I have a few thoughts:
> 
>     * ubuntu-latest [should](https://github.com/actions/runner-images#support-policy) have several pre-installed [python versions](https://github.com/actions/runner-images/blob/releases/ubuntu22/20230227/images/linux/Ubuntu2204-Readme.md#python), one of them should be sufficient for this job. So i wouldn't add a new action for that.

I thought it would be the best way to ensure the same settings as configured in [.pre-commit-config.yaml](https://github.com/ddionrails/ddionrails/blob/master/.pre-commit-config.yaml) and the same versions of the tools used as defined in [Pipfile.lock](https://github.com/ddionrails/ddionrails/blob/master/Pipfile.lock).  But feel free to install the tools directly. Also the setup-python action, when the job finishes, caches the installed dependencies, which I thought would be useful.

> 
>     * I would skip the Pipfile and install the needed tools directly.
> 
>     * I would call the tools directly, not through pre-commit.
> 
>     * I would run the tools only on changed files.

Yes, sure. That makes the run a little bit faster, but I wanted to point out that some files "sneaked" into the project, that now fail in the lint job.
> 
> 
> Addition to the last point: I have done this with GitLab Pipeline Jobs. There, the job gets an env var that contains the hash for the last commit. So you can use this to list changed files via the git cli. There does not seem to be such an env var in the GitHub Job. We could, from my understanding of it, parse this from the [PushEvent](https://docs.github.com/en/webhooks-and-events/events/github-event-types#pushevent) data, stored at [GITHUB_EVENT_PATH](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)
> 
> The hash from the PushEvent Data might also be available through a [different way](https://stackoverflow.com/questions/61860732/how-can-i-get-the-previous-commit-before-a-push-or-merge-in-github-action-workfl).

Feel free to close the PR.

**Pull request closed without merging**
