### PR TITLE
Add image_url to questions

### PR DESCRIPTION
**Pull request by mhebing**
We already enabled to show images for variables in WP 4 using a field `image_url`.

This update does two things:

1. Adding the same functionality for questions.
2. It allows to store multiple urls in the field image_url, separated by blanks.

### CODE REVIEW

**Comment by afuetterer** [comment]
The tests for importing a simple question failed. It lacks an image_url now, as the image_url attribute is set to blank=True but it cannot be null.
This should be easy to fix in the test data.

**Comment by afuetterer** [comment]
Also I don't like the approach of storing multiple urls in a text field called image_url as you describe in point 2
"It allows to store multiple urls in the field image_url, separated by blanks."
and in `question_detail.html`: "`{% for image_url in question.image_url.split %}`"

**Comment by afuetterer** [comment]
@hansendx The proposed nesting approach uses "separation by blanks".

**Comment by hansendx** [comment]
> @hansendx The proposed nesting approach uses "separation by blanks".

@afuetterer Sorry, I must have misremembered your comment while writing my own.
But I would not take this approach regardless of the character used to separate the URLs.

**Pull request closed without merging**
